services:
  postgres:
    image: postgres:16-alpine
    container_name: mangafire-db
    environment:
      POSTGRES_USER: mangafire
      POSTGRES_PASSWORD: mangafire
      POSTGRES_DB: mangafire
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U mangafire']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
